name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"

      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - uses: astral-sh/setup-uv@v9.0.0
        with:
          version: "latest"
          prune-cache: true

      - name: Check formatting
        run: make format-check

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - uses: astral-sh/setup-uv@v9.0.0
        with:
          version: "latest"
          prune-cache: true

      - name: Test
        run: make test
